/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as WorldsRenaissanceRouteImport } from './routes/worlds.renaissance'
import { Route as WorldsModernRouteImport } from './routes/worlds.modern'
import { Route as WorldsEgyptRouteImport } from './routes/worlds.egypt'
import { Route as WorldsAtlantisRouteImport } from './routes/worlds.atlantis'
import { Route as ApiGuideRouteImport } from './routes/api/guide'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsRenaissanceRoute = WorldsRenaissanceRouteImport.update({
  id: '/renaissance',
  path: '/renaissance',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsModernRoute = WorldsModernRouteImport.update({
  id: '/modern',
  path: '/modern',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsEgyptRoute = WorldsEgyptRouteImport.update({
  id: '/egypt',
  path: '/egypt',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsAtlantisRoute = WorldsAtlantisRouteImport.update({
  id: '/atlantis',
  path: '/atlantis',
  getParentRoute: () => WorldsRoute,
} as any)
const ApiGuideRoute = ApiGuideRouteImport.update({
  id: '/api/guide',
  path: '/api/guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/api/guide': typeof ApiGuideRoute
  '/worlds/atlantis': typeof WorldsAtlantisRoute
  '/worlds/egypt': typeof WorldsEgyptRoute
  '/worlds/modern': typeof WorldsModernRoute
  '/worlds/renaissance': typeof WorldsRenaissanceRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/guide': typeof ApiGuideRoute
  '/worlds/atlantis': typeof WorldsAtlantisRoute
  '/worlds/egypt': typeof WorldsEgyptRoute
  '/worlds/modern': typeof WorldsModernRoute
  '/worlds/renaissance': typeof WorldsRenaissanceRoute
  '/worlds': typeof WorldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/api/guide': typeof ApiGuideRoute
  '/worlds/atlantis': typeof WorldsAtlantisRoute
  '/worlds/egypt': typeof WorldsEgyptRoute
  '/worlds/modern': typeof WorldsModernRoute
  '/worlds/renaissance': typeof WorldsRenaissanceRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/worlds'
    | '/api/guide'
    | '/worlds/atlantis'
    | '/worlds/egypt'
    | '/worlds/modern'
    | '/worlds/renaissance'
    | '/worlds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/guide'
    | '/worlds/atlantis'
    | '/worlds/egypt'
    | '/worlds/modern'
    | '/worlds/renaissance'
    | '/worlds'
  id:
    | '__root__'
    | '/'
    | '/worlds'
    | '/api/guide'
    | '/worlds/atlantis'
    | '/worlds/egypt'
    | '/worlds/modern'
    | '/worlds/renaissance'
    | '/worlds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorldsRoute: typeof WorldsRouteWithChildren
  ApiGuideRoute: typeof ApiGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/renaissance': {
      id: '/worlds/renaissance'
      path: '/renaissance'
      fullPath: '/worlds/renaissance'
      preLoaderRoute: typeof WorldsRenaissanceRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/modern': {
      id: '/worlds/modern'
      path: '/modern'
      fullPath: '/worlds/modern'
      preLoaderRoute: typeof WorldsModernRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/egypt': {
      id: '/worlds/egypt'
      path: '/egypt'
      fullPath: '/worlds/egypt'
      preLoaderRoute: typeof WorldsEgyptRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/atlantis': {
      id: '/worlds/atlantis'
      path: '/atlantis'
      fullPath: '/worlds/atlantis'
      preLoaderRoute: typeof WorldsAtlantisRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/api/guide': {
      id: '/api/guide'
      path: '/api/guide'
      fullPath: '/api/guide'
      preLoaderRoute: typeof ApiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorldsRouteChildren {
  WorldsAtlantisRoute: typeof WorldsAtlantisRoute
  WorldsEgyptRoute: typeof WorldsEgyptRoute
  WorldsModernRoute: typeof WorldsModernRoute
  WorldsRenaissanceRoute: typeof WorldsRenaissanceRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
}

const WorldsRouteChildren: WorldsRouteChildren = {
  WorldsAtlantisRoute: WorldsAtlantisRoute,
  WorldsEgyptRoute: WorldsEgyptRoute,
  WorldsModernRoute: WorldsModernRoute,
  WorldsRenaissanceRoute: WorldsRenaissanceRoute,
  WorldsIndexRoute: WorldsIndexRoute,
}

const WorldsRouteWithChildren =
  WorldsRoute._addFileChildren(WorldsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorldsRoute: WorldsRouteWithChildren,
  ApiGuideRoute: ApiGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
